### ISSUE TITLE
Can I forward all traffic from WG tunnel to my default network interface?

### ISSUE THREAD

**Issue by capmorganbih** [vi/wgslirpy#2]
Do I really need to specify all ports I wanna forward TCP traffic from WG interface to outer world explicitly? Is there a way to say that any traffic with any port coming to WG interface should go to internet with same port?

**Comment by vi** [comment]
Forwarding traffic from WireGuard tunnel to outer world is the default mode of operation.

You need to specify explicit things to forward connections _from_ outer world _into_ WireGuard tunnel (while also forwarding everything in the reverse direction as usual). This is similar to SLiRP.

**Comment by vi** [comment]
> should go to internet with same port

All traffic seen on Wireguard tunnel is indeed converted to usual operating system's TCP or UDP sockets and directed to host and port taken from destination address seen on Wireguard-encapsupated packet. That includes "127.0.0.1" and other special addresses. Replies received from the socket are directed back to source address seen on the Wireguard-encapsupated packet.

Source port for outgoing connections is not affected by original source port, just chosen randomly by operating system.

**Comment by capmorganbih** [comment]
Thanks for clarifications !!!
